// ============================================================================
// File:        BuildStampEngine.cs
// Project:     Solcogito.BuildStamp
// Author:      Solcogito S.E.N.C.
// Description:
//     Public entry point for BuildStamp Core.
//     This is the ONLY execution surface exposed by the library.
// ============================================================================

using System;
using System.Text;

namespace Solcogito.BuildStamp;

public static class BuildStampEngine
{
    /// <summary>
    /// Executes BuildStamp using a fully-specified request.
    /// </summary>
    /// <remarks>
    /// This method is pure:
    /// - No filesystem access
    /// - No environment inspection
    /// - No console output
    ///
    /// Determinism guarantee:
    /// Same request => same result.
    /// </remarks>
    public static BuildStampResult Run(BuildStampRequest request)
    {
        if (request is null)
            throw new BuildStampException(
                BuildStampErrorCode.InvalidRequest,
                "Request cannot be null.");

        ValidateRequest(request);

        string ts = request.Timestamp.ToString("O");
        string project = request.Project;
        string version = request.Version;
        string branch = request.Branch ?? string.Empty;
        string commit = request.Commit ?? string.Empty;

        return request.Format switch
        {
            BuildStampFormat.Text => new BuildStampResult(
                Content: FormatText(project, version, branch, commit, ts),
                FileExtension: "txt"),

            BuildStampFormat.Json => new BuildStampResult(
                Content: FormatJson(project, version, branch, commit, ts),
                FileExtension: "json"),

            BuildStampFormat.Markdown => new BuildStampResult(
                Content: FormatMarkdown(project, version, branch, commit, ts),
                FileExtension: "md"),

            BuildStampFormat.CSharp => new BuildStampResult(
                Content: FormatCSharp(project, version, branch, commit, ts),
                FileExtension: "cs"),

            _ => throw new BuildStampException(
                BuildStampErrorCode.UnsupportedFormat,
                "Unsupported output format.")
        };
    }

    private static void ValidateRequest(BuildStampRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Project))
            throw new BuildStampException(
                BuildStampErrorCode.InvalidRequest,
                "Project cannot be null or empty.");

        if (string.IsNullOrWhiteSpace(request.Version))
            throw new BuildStampException(
                BuildStampErrorCode.InvalidRequest,
                "Version cannot be null or empty.");
    }

    private static string FormatText(
        string project,
        string version,
        string branch,
        string commit,
        string timestamp)
    {
        return
$@"Project:   {project}
Version:   {version}
Branch:    {branch}
Commit:    {commit}
Timestamp: {timestamp}";
    }

    private static string FormatJson(
        string project,
        string version,
        string branch,
        string commit,
        string timestamp)
    {
        // Deterministic, exact formatting matching golden outputs.
        // No serializer to avoid whitespace/ordering drift.
        var sb = new StringBuilder();
        sb.AppendLine("{");
        sb.AppendLine($"  \"Project\": \"{EscapeJson(project)}\",");
        sb.AppendLine($"  \"Version\": \"{EscapeJson(version)}\",");
        sb.AppendLine($"  \"Branch\": \"{EscapeJson(branch)}\",");
        sb.AppendLine($"  \"Commit\": \"{EscapeJson(commit)}\",");
        sb.AppendLine($"  \"Timestamp\": \"{EscapeJson(timestamp)}\"");
        sb.Append('}');
        return sb.ToString();
    }

    private static string FormatMarkdown(
        string project,
        string version,
        string branch,
        string commit,
        string timestamp)
    {
        return
$@"**Project:** {project}  
**Version:** {version}  
**Branch:** {branch}  
**Commit:** `{commit}`  
**Built:** {timestamp}";
    }

    private static string FormatCSharp(
        string project,
        string version,
        string branch,
        string commit,
        string timestamp)
    {
        return
$@"// Auto-generated by BuildStamp
namespace {project}.Build
{{
    internal static class BuildInfo
    {{
        public const string Version = ""{EscapeCSharpString(version)}"";
        public const string Branch  = ""{EscapeCSharpString(branch)}"";
        public const string Commit  = ""{EscapeCSharpString(commit)}"";
        public const string Timestamp = ""{EscapeCSharpString(timestamp)}"";
    }}
}}";
    }

    private static string EscapeJson(string value)
    {
        if (string.IsNullOrEmpty(value))
            return string.Empty;

        // Minimal JSON escaping for v0.1.0 contract:
        // backslash and quote, plus common control chars.
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n")
            .Replace("\t", "\\t");
    }

    private static string EscapeCSharpString(string value)
    {
        if (string.IsNullOrEmpty(value))
            return string.Empty;

        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");
    }
}
