// ============================================================================
// File:        BuildInfoTemplate.cs
// Project:     Solcogito.BuildStamp.Core
// Version:     0.6.0
// Author:      Solcogito S.E.N.C.
// Description: Template helper for BuildInfo.cs generation.
// ============================================================================

namespace Solcogito.BuildStamp.Core.Metadata
{
    internal static class BuildInfoTemplate
    {
        public static string Render(
            string ns,
            string className,
            string version,
            int major,
            int minor,
            int patch,
            string? pre,
            string? buildMeta,
            string? informationalVersion,
            string? commitSha,
            string? branch,
            string? timestampUtcIso,
            bool emitAssemblyAttributes)
        {
            var preStr = pre ?? string.Empty;
            var metaStr = buildMeta ?? string.Empty;
            var infoVer = informationalVersion ?? version;

            var attrs = emitAssemblyAttributes
                ? $@"using System.Reflection;
[assembly: AssemblyMetadata(""Build.Version"", ""{version}"")]
[assembly: AssemblyMetadata(""Build.InformationalVersion"", ""{infoVer}"")]
[assembly: AssemblyMetadata(""Build.CommitSha"", ""{commitSha ?? ""}"")]
[assembly: AssemblyMetadata(""Build.Branch"", ""{branch ?? ""}"")]
[assembly: AssemblyMetadata(""Build.TimestampUtc"", ""{timestampUtcIso ?? ""}"")]
"
                : string.Empty;

            return
$@"// <auto-generated />
// Generated by BuildStamp v0.6.0
{attrs}
namespace {ns}
{{
    internal static class {className}
    {{
        public const string Version = ""{version}"";
        public const int VersionMajor = {major};
        public const int VersionMinor = {minor};
        public const int VersionPatch = {patch};
        public const string VersionPrerelease = ""{preStr}"";
        public const string VersionBuildMeta = ""{metaStr}"";
        public const string InformationalVersion = ""{infoVer}"";
        public const string CommitSha = ""{commitSha ?? ""}"";
        public const string Branch = ""{branch ?? ""}"";
        public const string TimestampUtc = ""{timestampUtcIso ?? ""}"";
    }}
}}
";
        }
    }
}
