// ============================================================================
// File:        CsFormatter.cs
// Project:     Solcogito.BuildStamp
// Author:      Solcogito S.E.N.C.
// Description: Generates C# source file embedding build constants.
// ============================================================================

namespace Solcogito.BuildStamp.Output;

public class CsFormatter : IOutputFormatter
{
    public string Extension => "cs";

    public string Format(BuildInfo info)
    {
        return
$@"// Auto-generated by BuildStamp
namespace {info.Project}.Build
{{
    internal static class BuildInfo
    {{
        public const string Version = ""{info.Version}"";
        public const string Branch  = ""{info.Branch}"";
        public const string Commit  = ""{info.Commit}"";
        public const string Timestamp = ""{info.Timestamp}"";
    }}
}}";
    }
}
