// ============================================================================
// File:        BuildStampGoldenSamples.cs
// Project:     Solcogito.BuildStamp.Tests
// Author:      Solcogito S.E.N.C.
// Description:
//     Golden reference outputs for BuildStamp Core.
//     These values define the public contract.
// ============================================================================

using System;

namespace Solcogito.BuildStamp.Tests;

internal static class BuildStampGoldenSamples
{
    public static readonly DateTimeOffset Timestamp =
        new DateTimeOffset(2025, 01, 01, 12, 00, 00, TimeSpan.Zero);

    public const string Project = "DemoProject";
    public const string Version = "1.2.3";
    public const string Branch = "main";
    public const string Commit = "abc123";

    // --------------------------------------------------------------------
    // TEXT
    // --------------------------------------------------------------------

    public const string Text =
@"Project:   DemoProject
Version:   1.2.3
Branch:    main
Commit:    abc123
Timestamp: 2025-01-01T12:00:00.0000000+00:00";

    // --------------------------------------------------------------------
    // JSON
    // --------------------------------------------------------------------

    public const string Json =
@"{
  ""Project"": ""DemoProject"",
  ""Version"": ""1.2.3"",
  ""Branch"": ""main"",
  ""Commit"": ""abc123"",
  ""Timestamp"": ""2025-01-01T12:00:00.0000000+00:00""
}";

    // --------------------------------------------------------------------
    // MARKDOWN
    // --------------------------------------------------------------------

    public const string Markdown =
@"**Project:** DemoProject  
**Version:** 1.2.3  
**Branch:** main  
**Commit:** `abc123`  
**Built:** 2025-01-01T12:00:00.0000000+00:00";

    // --------------------------------------------------------------------
    // C#
    // --------------------------------------------------------------------

    public const string CSharp =
@"// Auto-generated by BuildStamp
namespace DemoProject.Build
{
    internal static class BuildInfo
    {
        public const string Version = ""1.2.3"";
        public const string Branch  = ""main"";
        public const string Commit  = ""abc123"";
        public const string Timestamp = ""2025-01-01T12:00:00.0000000+00:00"";
    }
}";
}
